### ISSUE TITLE
RAM_Toolkit: Adapting to changes in BHoMAdapter

### ISSUE THREAD

**Issue by enarhi** [BHoM/RAM_Toolkit#106]
#### Parent issue(s) or Pull Request(s) causing the changes:

https://github.com/BHoM/BHoM_Adapter/pull/151

#### Description:
Updating toolkit to align with refactoring of the parent BHoMAdapter (CRUD folder reformatting)

**Comment by FraserGreenroyd** [comment]
@enarhi is this not closed by #104 ?

**Comment by enarhi** [comment]
We have lingering compliance changes that need to be tracked through. #104 closed the main issue so we have a working build but I still need to clean up the crud folder per @alelom 's followup guidance.

**Comment by FraserGreenroyd** [comment]
Ok that makes sense, just thought I'd double check :smile:
