### ISSUE TITLE
Versioning didn't work for the deleted ContourLoadSet method 

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/RAM_Toolkit#184]
@JosefTaylor Versioning does not appear to have worked for the contour load set (though it did for the uniform load set). I'm getting the generic "This is a magic component" message.

![image](https://user-images.githubusercontent.com/58230980/115313763-b907ec00-a128-11eb-8495-5f38f4eec67a.png)

_Originally posted by @maryannewachter in https://github.com/BHoM/RAM_Toolkit/issues/183#issuecomment-822844586_

**Comment by enarhi** [comment]
Closing as an outdated versioning issue.
