### ISSUE TITLE
Rename RAMFactoredEndReactions to RAMServiceEndReactions (or just get rid of it; it's useless)

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/RAM_Toolkit#191]
#### Description:

This appears to be a bug in the API. 
the method GetMaximumComboReactions() takes an argument of type COMBO_MATERIAL_TYPE
The API docs state that only COMBO_MATERIAL_TYPE.STEEL_GRAV is implemented, however that enum does not exist. The similar enum, COMBO_MATERIAL_TYPE.GRAV_STEEL, is the only enum value which allows the method to return a value, and the value returned is the un-factored, or service level, reaction.

**Comment by JosefTaylor** [comment]
wrote to Bentley support, they say yep, it's service level, and they have no plans to make other combos available. This needs to be noted on our side to prevent confusion.

**Comment by enarhi** [comment]
Noting for clarity, we have shifted to pulling from the RAM API method which returns Factored Gravity Loads (matches what is shown in the UI when showing Factored Loads).
