### ISSUE TITLE
RAM_Toolkit: Add more custom data to pull

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/RAM_Toolkit#39]
Adding FloorType to Beam and Horizontal Brace custom data. A few more things we should add:
- [ ] Story for all members and panels
- [ ] releases
- [ ] cantilevers
- [ ] bracing
- [ ] frametype
- [ ] materials
- [ ] other stuff

**Comment by enarhi** [comment]
@JosefTaylor I am closing as a chunk of this is already taken care of, and the rest will be affected by #71 . Let's revisit custom data after that to narrow it down to what is required based on our experience with current RAM_Toolkit applications.
