### ISSUE TITLE
RAM_Toolkit: Grids do not come in

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/RAM_Toolkit#68]
See test script: https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/RAM_Toolkit/RAM_Toolkit%20Issue68%20Grids%20do%20not%20come%20in?csf=1&e=5mXJre

**Comment by enarhi** [comment]
Closed with #67
